package com.sem.lamoot.elati.danstonplacard.danstonplacard.database.model;

public enum Rayon {
    SURGELE, BIO, FRUITS_LEGUMES, BOISSONS, BOULANGERIE_PATISSERIE,
    CREMERIE, YAOURTS_DESSERTS, FROMAGES, VIANDES, POISSONS_CRUSTACES, EPICERIE_SUCREE, EPICERIE_SALEE,
    BEAUTE, DIVERS;
}
